--- # httpd server installation
- hosts: app_server
  user: venu
  sudo: yes
  tasks:
   - name: install httpd
     yum: name=httpd state=installed
   - name: copy index file
     copy: src=simple.index.html dest=/var/www/html/index.html
   - name: start service
     service: name=httpd state=started 
