--- # httpd server installation
- hosts: web_server
  user: venu
  become_user: yes
  tasks:
   - name: install httpd
     yum: name=httpd state=installed
   - name: start service
     service: name=httpd state=started 
